### ISSUE TITLE
first running gives an error on windows 

### ISSUE THREAD

**Issue by nolines** [ncamacho/gitlab_clone#2]
C:/Ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': ca
nnot load such file -- rainbow (LoadError)
        from C:/Ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in
`require'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/gitlab_clone-0.12.1/lib/setup.rb
:2:in `<class:Setup>'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/gitlab_clone-0.12.1/lib/setup.rb
:1:in `<top (required)>'
        from C:/Ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in
`require'
        from C:/Ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in
`require'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/gitlab_clone-0.12.1/lib/gitlab.r
b:2:in `<class:Gitlab>'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/gitlab_clone-0.12.1/lib/gitlab.r
b:1:in `<top (required)>'
        from C:/Ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in
 `require'
        from C:/Ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in
 `rescue in require'
        from C:/Ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in
`require'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/gitlab_clone-0.12.1/bin/gitlab-c
lone:7:in `<top (required)>'
        from C:/Ruby23/bin/gitlab-clone:22:in `load'
        from C:/Ruby23/bin/gitlab-clone:22:in `<main>'

**Comment by nolines** [comment]
`gem install rainbow` -v 2.1.0 must install rainbow from external. Maybe package should contain rainbow inside of gem package?

**Comment by ncamacho** [comment]
Hmm... will have to test this out this week. I actually did not test this in windows :).

**Comment by mikejhale** [comment]
I ran into this too but resolved it with `gem install rainbow`

Installing rainbow requires the [Ruby DevKit](http://rubyinstaller.org/add-ons/devkit/) to be installed as well. Once I downloaded and installed that I was able to install Rainbow and get this working.
